### PR TITLE
Add lita-nashdev-resources plugin

### PR DESCRIPTION
**Pull request by maxbeizer**
A [lita](https://lita.io) plugin to allow people to suggest resources to be added to the [NashDev Resources repo](https://github.com/maxbeizer/nashdev-resources) via GitHub Issues.

What do you think @sciurus ? If you :+1: , I'll send you the required token.

### CODE REVIEW

**Comment by sciurus** [comment]
Sorry @maxbeizer , I've been distracted by :baby: and the end of my paternity leave.

maxbeizer/lita-nashdev-resources looks :cool: and I would love to merge this and get it deployed!

Should your PR have a change to lita_config.rb to load the token?

**Comment by maxbeizer** [comment]
Heh. Yeah good point. I'll update it later today. Thanks!

**Comment by maxbeizer** [comment]
@sciurus updated to set the config var in `lita_config.rb`

**Comment by sciurus** [comment]
You can GPG encrypt and send me the token; I'm on Keybase.

**Pull request merged**
